name: 'Install msys2'
description: 'Prepares msys2 for Windows builds.'
runs:
  using: composite
  steps:
  - name: Setup msys2
    uses: msys2/setup-msys2@v2
    id: msys2
    with:
      path-type: inherit # Important to correctly update PATH
      install: >-
        base-devel
        git
        mingw-w64-x86_64-clang
        mingw-w64-x86_64-lld
        mingw-w64-x86_64-rust
        mingw-w64-x86_64-cmake
        mingw-w64-x86_64-ninja
        mingw-w64-x86_64-gcc
        mingw-w64-x86_64-gcc-libs
        mingw-w64-x86_64-python

  - name: Prepare env
    shell: 'msys2 {0}'
    env:
      MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
    run: |
      echo "/c/a/_temp/msys64/mingw64/bin" >> "${GITHUB_PATH}"
      echo "/c/Users/runneradmin/.cargo/bin" >> "${GITHUB_PATH}"
