name: 'Build solc'
description: 'Builds solc executable.'
inputs:
  release-suffix:
    description: 'Release suffix.'
    required: false
    default: ''
  zksync-version:
    description: 'Release version.'
    required: true
  solc-version:
    description: 'Solidity version.'
    required: true
  build-type:
    description: 'Build type: candidate or reference'
    required: false
    default: 'candidate'
  extra-args:
    description: 'Extra arguments for cmake.'
    required: false
    default: ''
  boost-version:
    description: 'Boost version.'
    required: false
    default: '1.74.0'
runs:
  using: "composite"
  steps:

    - name: Install Boost (MacOS and Linux)
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      env:
        BOOST_VERSION: ${{ inputs.boost-version }}
        BOOST_DOWNLOAD_URL: "https://boostorg.jfrog.io/artifactory/main/release/${{ inputs.boost-version }}/source"
      run: |
        [ ${RUNNER_OS} = macOS ] && PARALLEL=$(sysctl -n hw.ncpu) || PARALLEL=$(nproc)
        BOOST_FILENAME=boost_${BOOST_VERSION//./_}
        curl -L -o ${BOOST_FILENAME}.tar.gz "${BOOST_DOWNLOAD_URL}/${BOOST_FILENAME}.tar.gz"
        tar xzf "${BOOST_FILENAME}.tar.gz" && cd ${BOOST_FILENAME}
        if [ ${RUNNER_OS} = macOS ]; then
          if [ ${RUNNER_ARCH} = X64 ]; then
            ./bootstrap.sh --prefix=${PWD}/../boost --with-python-version=2.7
          else
            ./bootstrap.sh --prefix=${PWD}/../boost
          fi
        else
          # Only relative boost prefix is working on Windows MSYS2
          ./bootstrap.sh --prefix="../boost"
        fi
        ./b2 link=static runtime-link=static variant=release threading=multi address-model=64 --with-filesystem --with-system --with-program_options --with-test -j${PARALLEL} install

    - name: Build solc
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      env:
        CXXFLAGS: "-Wno-narrowing"
        BOOST_VERSION: ${{ inputs.boost-version }}
      run: |
        set -x
        if [ ${RUNNER_OS} = macOS ]; then
          PARALLEL=$(sysctl -n hw.ncpu)
          if [ ${RUNNER_ARCH} = X64 ]; then
            BOOST_VERSION=${BOOST_VERSION//./_}
            BOOST_SHORT_VERSION=${BOOST_VERSION%??}
            BOOST_ROOT="${PWD}/boost/lib/cmake/Boost-${BOOST_VERSION}"
            BOOST_LIBDIR="${PWD}/boost/lib"
            BOOST_INCLUDEDIR="${PWD}/boost/include"
            BOOST_CMAKE_FLAGS="-DBoost_COMPILER=clang -DBoost_NO_BOOST_CMAKE=1 -DBoost_NO_SYSTEM_PATHS=1 -DBOOST_ROOT=${BOOST_ROOT} -DBOOST_LIBRARYDIR="${BOOST_LIBDIR}" -DBoost_USE_STATIC_RUNTIME=1 -DBOOST_USE_STATIC_LIBS=1 -DBOOST_INCLUDEDIR="${BOOST_INCLUDEDIR}" -DBoost_DEBUG=1"
            #cd ${BOOST_LIBDIR}
            #for BOOST_LIB in lib*.a; do
            #  mv "${BOOST_LIB}" "${BOOST_LIB#lib}"
            #done
            #cd -
            find ${PWD}/boost
            ls -la ${BOOST_INCLUDEDIR}
          fi
        else
          PARALLEL=$(nproc)
        fi
        if [ ${RUNNER_OS} = Linux ]; then
          COMPILER_FLAGS="-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS=-fuse-ld=lld"
        fi
        if [ ${RUNNER_OS} = Windows ]; then
          COMPILER_FLAGS="-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DUSE_LD_GOLD=OFF -DCMAKE_CXX_FLAGS=-fuse-ld=lld"
          export LDFLAGS='-lbcrypt -lwsock32 -static'
          BOOST_VERSION=${BOOST_VERSION//./_}
          BOOST_SHORT_VERSION=${BOOST_VERSION%??}
          BOOST_ROOT="${PWD}/boost/lib/cmake/Boost-${BOOST_VERSION}"
          BOOST_LIBDIR="${PWD}/boost/lib"
          BOOST_INCLUDEDIR="${PWD}/boost/include/boost-${BOOST_SHORT_VERSION}"
          BOOST_CMAKE_FLAGS="-DBoost_NO_BOOST_CMAKE=1 -DBoost_NO_SYSTEM_PATHS=1 -DBOOST_ROOT=${BOOST_ROOT} -DBOOST_LIBRARYDIR="${BOOST_LIBDIR}" -DBOOST_USE_STATIC_RUNTIME=1 -DBOOST_USE_STATIC_LIBS=1 -DBOOST_INCLUDEDIR="${BOOST_INCLUDEDIR}" -DBoost_DEBUG=1"
          # Rename boost libraries to match the expected names
          # even with BOOST_COMPILER=mgw14, CMake still unable to find the libraries
          for file in ${BOOST_LIBDIR}/*-mgw14-mt-s-x64-${BOOST_SHORT_VERSION}.a; do
            mv "$file" "${file%-mgw14-mt-s-x64-$BOOST_SHORT_VERSION.a}.a"
          done
        fi

        ls -la ${BOOST_LIBDIR}

        mkdir -p ./build
        cd ./build
        cmake .. \
          -DCMAKE_BUILD_TYPE="Release" ${COMPILER_FLAGS} ${BOOST_CMAKE_FLAGS} \
          -DSOL_VERSION_ZKSYNC="${{ inputs.solc-version }}-${{ inputs.zksync-version }}" \
          -DSOLC_VERSION_ZKEVM="${{ inputs.solc-version }}-${{ inputs.zksync-version }}" \
          -DSOL_VERSION_ZKEVM="${{ inputs.solc-version }}-${{ inputs.zksync-version }}" \
          -DUSE_Z3=OFF \
          -DUSE_CVC4=OFF \
          -DTESTS=0 \
          -DSOLC_LINK_STATIC=1 \
          -DSTATIC_LINKING=1 \
          -DPEDANTIC=OFF ${{ inputs.extra-args}}
        if [[ ${{ inputs.solc-version}} == "0.4"* ]]; then
          cmake --build . --config Release --parallel ${PARALLEL} --target jsoncpp-project
          cmake --build . --config Release --parallel ${PARALLEL} --target range-v3-project
        fi
        cmake --build . --config Release --parallel ${PARALLEL} --target solc
        [ "$RUNNER_OS" = "Windows" ] && WIN_SUFFIX=".exe"
        cp ./solc/solc${WIN_SUFFIX} ./solc/solc-${{ inputs.solc-version }}-${{ inputs.build-type }}${WIN_SUFFIX}

    - name: Upload binary for testing
      if: inputs.release-suffix == ''
      uses: actions/upload-artifact@v4
      with:
        name: solc-${{ inputs.solc-version }}-${{ inputs.build-type }}
        path: ./build/solc/solc-${{ inputs.solc-version }}-${{ inputs.build-type }}

    - name: Prepare binary
      if: inputs.release-suffix != ''
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: |
        [ "$RUNNER_OS" = "Windows" ] && WIN_SUFFIX=".exe"
        SOLC_BIN="./build/solc/solc${WIN_SUFFIX}"
        mkdir -p ./releases/${{ inputs.release-suffix }}
        strip "${SOLC_BIN}"
        ${SOLC_BIN} --version
        mv ${SOLC_BIN} ./releases/${{ inputs.release-suffix }}/solc-${{ inputs.release-suffix }}-${{ inputs.solc-version}}-${{ inputs.zksync-version }}${WIN_SUFFIX}

    - name: Upload binary for release
      if: inputs.release-suffix != ''
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ inputs.release-suffix }}
        path: releases
