name: Solc build and release

on:
  workflow_call:

concurrency:
  group: ${{ github.repository_id }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      solc-version: ${{ steps.set.outputs.solc-version }}
      zksync-version: ${{ steps.set.outputs.zksync-version }}
      use-new-tools: ${{ steps.use-new-tools.outputs.result }}
      use-gcc: ${{ steps.use-gcc.outputs.result }}
      use-windows-clang: ${{ steps.use-windows-clang.outputs.result }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Define release version
        shell: bash
        id: set
        run: |
          if [[ ${{ github.event_name }} != 'pull_request' ]]; then
            echo "zksync-version=$(cut -d "-" -f2 <<< ${GITHUB_REF#refs/*/})" | tee -a "${GITHUB_OUTPUT}"
          else
            echo "zksync-version=1.0.${{ github.run_id }}" | tee -a "${GITHUB_OUTPUT}"
          fi
          SOLC_VERSION=$(grep 'PROJECT_VERSION' CMakeLists.txt | grep -oP '(\d+\.\d+\.\d+)')
          echo "solc-version=${SOLC_VERSION}" | tee -a "${GITHUB_OUTPUT}"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install semver
        run: npm install semver

      - name: Check that version is <= 0.4.16
        id: use-gcc
        uses: actions/github-script@v7
        with:
          script: |
            const semver = require('semver');
            const currentVersion = '${{ steps.set.outputs.solc-version }}';
            const result = semver.lte(currentVersion, '0.4.16');
            console.log(`Is the version <= 0.4.16? ${result}`);
            return result;
          result-encoding: string

      - name: Check that version is >= 0.5.1
        id: use-new-tools
        uses: actions/github-script@v7
        with:
          script: |
            const semver = require('semver');
            const currentVersion = '${{ steps.set.outputs.solc-version }}';
            const result = semver.gte(currentVersion, '0.5.1');
            console.log(`Is the version >= 0.5.1? ${result}`);
            return result;
          result-encoding: string

      # TODO: identify the exact version instead of 0.8.19
      - name: Check that version is >= 0.8.19
        id: use-windows-clang
        uses: actions/github-script@v7
        with:
          script: |
            const semver = require('semver');
            const currentVersion = '${{ steps.set.outputs.solc-version }}';
            const result = semver.gte(currentVersion, '0.8.19');
            console.log(`Is the version >= 0.8.19? ${result}`);
            return result;
          result-encoding: string

  build:
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "MacOS x86"
            runner: macos-latest-large
            release-suffix: macosx-amd64
          - name: "MacOS arm64"
            runner: macos-latest-xlarge
            release-suffix: macosx-arm64
          - name: "Linux x86"
            runner: matterlabs-ci-runner-high-performance
            image: ${{ needs.setup.outputs.use-new-tools == 'true' && 'ghcr.io/matter-labs/zksync-llvm-runner:latest' || 'matterlabs/llvm_runner:ubuntu20-llvm17-latest' }}
            release-suffix: linux-amd64
          - name: "Linux ARM64"
            runner: matterlabs-ci-runner-arm
            image: ${{ needs.setup.outputs.use-new-tools == 'true' && 'ghcr.io/matter-labs/zksync-llvm-runner:latest' || 'matterlabs/llvm_runner:ubuntu20-llvm17-latest' }}
            release-suffix: linux-arm64
          - name: Windows
            runner: windows-2019-github-hosted-64core
            release-suffix: windows-amd64
    runs-on: ${{ matrix.runner }}
    container:
      image: ${{ matrix.image || '' }}
    name: ${{ matrix.name }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare Windows env
        if: runner.os == 'Windows'
        uses: matter-labs/era-compiler-ci/.github/actions/prepare-msys@main

      - name: Building the Solidity compiler
        uses: matter-labs/era-compiler-ci/.github/actions/build-solc@main
        with:
          release-suffix: ${{ matrix.release-suffix }}
          zksync-version: ${{ needs.setup.outputs.zksync-version }}
          solc-version: ${{ needs.setup.outputs.solc-version }}
          boost-version: ${{ needs.setup.outputs.use-new-tools == 'true' && '1.83.0' || '1.71.0' }}
          use-gcc: ${{ needs.setup.outputs.use-gcc }}
          use-windows-clang: ${{ needs.setup.outputs.use-windows-clang }}

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: release*
          path: releases

      - name: Generate changelog
        shell: bash
        run: awk '/###/ {flag=!flag; if (seen++) exit; next} flag' ./Changelog.md > release-changelog.txt

      - name: Prepare release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: false
          name: ZKsync solc ${{ github.ref_name }}
          body_path: release-changelog.txt
          tag_name: ${{ github.ref_name }}
          files: releases/**/**
